gosnmp/gosnmp

- marshal.go
The err variable was erroneously (re)created in the scope of the loop body. While this didn't affect returning it from the loop, the non-fatal err assignments from the loop to the outer scope variable were now masked, resulting in (nil, nil) function returns, which causes a panic in walk.go:47 when a field in the nil result is accessed.
> very subtle scoping issue

- examples/walkexample.go
This example is a very quick test to confirm
a device can be walked successfully. As most devices
don't have a default community string of "public", better
to make it an extra arg to facilitate testing.
> Add community argument to walkexample

- helper.go
ITU X.690 8.3.1 says that integers should be encoded into 1 or more octets; gosnmp currently encodes zero-value integers into 0 octets, which causes it to fail miserably on certain enterprise-grade devices. Associated pull request fixes this issue.
> Fix integer zero value encoding

- gosnmp.go
- marshal.go
- marshal_test.go
fixes #68 
----
As an unrelated note, it happens at numerous places in the code where a method is called on a struct, and is passed members of itself as arguments.
For example in the previous code that this PR replaced:
x.dispatch(x.Conn, outBuf, expected)
Why not have the `dispatch` method just access `x.Conn` itself instead of passing it?
Other example:
packetOut.marshalMsg(pdus, packetOut.PDUType, msgID, reqID)
`packetOut` is a [SnmpPacket](https://godoc.org/github.com/soniah/gosnmp#SnmpPacket) in which `.Variables` can replace the `pdus` argument. `.PDUType` can replace the `packetOut.PDUType` argument, `.MsgID` can replace the `msgID` argument, and `.RequestID` can replace the `reqID` argument.
And numerous similar examples.
I think it would make the code easier for contributors to …
> handle receiving duplicate packets

- generic_e2e_test.go
Requiring a running and functional SNMPd on the system is a problematic
requirement in many environments (such as distribution build networks),
and might conflict with running instances that cannot be reconfigured.
I stumbled on this when preparing Debian packages for this project.
> Skip the test suite if the environment variables are missing

- examples/trapserver.go
- helper.go
- marshal.go
- trap.go
1. Trap example panics because TrapListener.c *sync.Cond is nil, switch to NewTrapListener()
2. TrapListener does not log anything because validateParameters() isn't called in Listen(). Fix this.
3. Add support for receiving V1 traps
> Add V1 traps, fix examples, fix TrapListener logging

- trap.go
i'm wrote my own snmp-trap daemon over your gosnmp package. But i have big problem with testing  - i can't feed my parser directly from tcpdump's output, because unmarshalTrap is private. 
now i can read output of 'tcpdump -n -x -r file'  :
func ParseDumpedPacket(hdr *string, hexPayload *bytes.Buffer){
payLoad,err := hex.DecodeString(hexPayload.String()[28*2:])
check(err)
pkt := g.Default.UnmarshalTrap(payLoad)
myTrapHandler(pkt)
}
> rename unmarshalTrap to UnmarshalTrap for better external testing

- marshal.go
I was running into odd hangs while trying to getbulk firewall counters from a junos device. gosnmp was generating invalid snmp requests for OIDs with >= 127 parts. Some diffing with captures from the command line tools lead me to the lengths. Unfortunately I don't have time to understand ASN.1 and BER encoding in depth so this fix may be incomplete. I guess I'll add the obligatory "it works for my use case" warning.
> More correctly marshal varbinds for Null PDUs with long OIDs

- trap.go
- trap_test.go
* Added the `Listening()` method on the `TrapListener` to allow the user code to check if the listener is ready to receive requests. Useful for testing `SendTrap` in user scenarios.
* Removed `sync.Cond` and `ready()` because they duplicate the purpose of the introduced `listening` channel; also removed the `listening bool` variable because its `listening=false` value is not used anywhere in tests.
* Replaced the `t.Fatalf` with an error channel to satisfy the `staticcheck` warnings:
```
trap_test.go:163:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
trap_test.go:224:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
```
* Satisfied the `go vet` and `golint` warnings:
```
trap_test.go:116: arg …
```
> Method that returns a channel that can be used to block until the TrapListener is ready

- README.md
Added package installation notice for go **dep** tool.
fixes: #136
> docs: add dep tool installation notice

- trap.go
A very minor bug fix that didn't occur to me earlier.
If ReadFromUDP errors for whatever reason when Close _hasn't_ been called, we still shouldn't try to unmarshal the data.
> Don't proceed to unmarshal trap after ReadFromUDP errors

- gosnmp.go
This PR exposes two public functions that allow packet encoding and decoding outside of the transport calls. This is useful when you want to play with SNMP packets without sending them through gosnmp. The atomic AddUint32s should probable be converted to AddUint64 and a mask, but that would be better done in a second PR so that it is consistent across the project.
> Expose SnmpEncodePacket/SnmpDecodePacket

- gosnmp.go
- marshal.go
- v3.go
This changeset enables better support for SNMPv3 in `SnmpEncodePacket()` and `SnmpDecodePacket()` by supporting `SecurityParameters`, exposing `SetMsgID`/`SetRequestID`/`MsgMaxSize`, and calling the `validateParameters()` function.
> Support SNMPv3 Encode/Decode

- helper.go
- helper_test.go
A problem existed where integers between 128 and 255 inclusive were being improperly encoded. 
The cause was the removed code, which was lopping off zeroed bytes. Those bytes were necessary to recognize as full int32 by receiving devices. Without them, the single byte was treated as int8 - below 128 and values are same as int32. Above 255 and you're into int16 which is the same.
I suspect another issue would have happened at the boundaries around signed int16s.
> Removed bit-lopping

- marshal.go
Hi,
This pull request corrects a few incorrect uses of logPrint() with formatting and logPrintf() without formatting.
These errors are located in marshal.go and were not found anywhere else.
Best Regards,
Vallimamod Abdullah
.
> fix incorrect logPrint & logPrintf usage

- v3.go
Gives a meaningful error message when user (me) is misusing the api :-)
Consider the following
```go
package snmptest
import (
"fmt"
"log"
"testing"
"time"
"github.com/soniah/gosnmp"
)
func TestSNMP(t *testing.T) {
params := &gosnmp.GoSNMP{
Target:    "172.16.72.143",
Port:      161,
Version:   gosnmp.Version3,
Community: "public",
Timeout:   time.Duration(1) * time.Second,
// v3 - noauth:
SecurityModel: gosnmp.UserSecurityModel,
MsgFlags:      gosnmp.NoAuthNoPriv,
/*
SecurityParameters: &gosnmp.UsmSecurityParameters{UserName: "authOnlyUser",
AuthenticationProtocol:   gosnmp.SHA,
AuthenticationPassphrase: "password",
},*/
}
err := params.Connect()
if err != nil {
log.Fatalf("SNMP Connect() err: %v", err)
}
defer params.Conn.Close()
...
}
```
Without this patch, the above code explodes …
> v3: avoid crash on missing SecurityParameters

- walk.go
call the walkFn before breaking the loop if the rootOid is an instance itself.
> fix: issue #170 (walk on leaf OID)

- v3.go
v3.go:
- Allows trap for initial param discovery.
- Allow initial param discovery with ContextName
fix: https://github.com/soniah/gosnmp/issues/145
Test available at https://github.com/slayercat/GoSNMPServer/blob/d00d4db40ff320b992fec9d9d72d69b66304559f/snmpserverTraps_test.go#L134
> v3.go: allow trap for initial param discovery

- v3_usm.go
Signed-off-by: Kian Ostvar <kiano@jurumani.com>
We are using Prometheus for a monitoring project that we are busy with and one of the requirements was monitoring Cisco devices using SNMP v3 for which we are currently using Prometheus' snmp_exporter. 
Some of the devices we need to monitor are configured to use AES256 privacy protocol and we noticed early on that the exporter was not able to communicate with those devices. So we started investigating by doing lots of packet captures and finally got the conclusion that the snmp library that the exporter 
is using does not support AES256. So we started learning Golang in order to add the functionality to 
gosnmp and here are the results. 
We noticed that in order to make this work, we needed to implement specific key extension algorithms to …
> Abstract AES implementation

- gosnmp.go
- trap_test.go
- v3_usm.go
If sp.AuthoritativeEngineID matches insp.AuthoritativeEngineID, then SecretKey and PrivacyKey are not generated. Therefore, receiving and sending authenticated and/or encrypted packets fails.
The pull request fixes the issue by not having key generation depending on the AuthoritativeEngineID-condition and altering how security parameters are set when sending traps.
I also added tests for SNMPv3 Traps and it passes all local tests.
> Fixed a bug with PrivacyKey and SecretKey calculation

- examples/trapsend_v3.go
- go.mod
- gosnmp.go
- v3.go
- v3_usm.go
This PR fixes issues mentioned in #229 and #228 
The root cause of those issues was a quick and dirty attempt to fix sending SNMPv3 traps without discovery packets, which can be seen in gosnmp.go
The issue which I was originally trying to solve, was that when AuthoritativeEngineID was specified, the keys for privacy and authenticity were not generated. If AuthoritativeEngineID is not specified, then a discovery packet is sent, and the returning packet triggers the generation of previously mentioned keys. As the discovery is not required if AuthoritativeEngineID is specified, then the keys are not generated.
The correct way to fix this would be to check if discovery is needed, and if it is not, then initialize those keys.This PR implements this kind of logic. I've also included …
> Fixes #229 and #228

- gosnmp.go
The semantics were changed by cd9a07ae5a52ff5851e1cfed624e5415b6e9a6ee
This was discovered in https://github.com/prometheus/snmp_exporter/issues/507
> Update Retries comment to reflect code.

- .travis.yml
- CHANGELOG.md
- Dockerfile
- README.md
- examples/example/main.go
- examples/example2/main.go
- examples/example3/main.go
- examples/tcp_trapserver/main.go
- examples/trapsend_v1/main.go
- examples/trapsend_v2plus/main.go
- examples/trapsend_v3/main.go
- examples/trapserver/main.go
- examples/walkexample/main.go
- examples/walktcpexample/main.go
- go.mod
- gosnmp.go
- gosnmp_api_test.go
- mocks/gosnmp_mock.go
Update references to github URLs to the new `gosnmp` organization.
* Cleanup README a bit.
Closes: https://github.com/gosnmp/gosnmp/issues/247
> Update github references

- CHANGELOG.md
This release updates the Go import path from `github.com/soniah/gosnmp`
to `github.com/gosnmp/gosnmp`.
* [CHANGE] Update project path #257
* [ENHANCEMENT] Improve SNMPv3 trap support #253
> Release v1.28.0

- v3_usm.go
Restored crypto import as suggested by @StefanHauth
Fixes #236 (https://github.com/gosnmp/gosnmp/issues/236): broken v3 authentication
> Restores crypto imports

- CHANGELOG.md
- generic_e2e_test.go
- helper.go
- marshal_test.go
- trap_test.go
Since we don't know the encoding of OctetString, return as a raw []byte
rather than a string.
Reverts commit 3336f959f5694e60191e2378cda0c47e68d01211
> Return OctetString as []byte

- gosnmp.go
Deprecate ``math/rand`` in favor of ``crypto/rand``
Fixes #267
> gosnmp.go: Deprecate math/rand

- gosnmp.go
- marshal.go
- marshal_test.go
Some of the multihomed network devices are not smart enough:
1. You can't set a routable loopback on them
2. You can't designate the snmp response address
3. You can't tell them to sent the packet from the address they received it from
As the result, if you use connected socket, responses can't reach it.
Fortunately the workaround is very simple. I also haven't found any downside of using
it with devices that operate correctly.
> Work around devices responding from different addr

- README.md
* Update [Documentation](https://github.com/gosnmp/gosnmp#documentation) link to use pkg.go.dev as godoc.org links will be [redirected](https://blog.golang.org/godoc.org-redirect) soon.
* Bump year in README [license](https://github.com/gosnmp/gosnmp#license)
> README.md Update documentation link to use go.dev

- README.md
- generic_e2e_test.go
- gosnmp.go
Changed GetBulk so it returns an explicit error when called with Version1.
Added matching test.
Documented GETBULK support in README.md
Added SNMPv1 as explicitely supported in README.
Fixes #288
> return error when GETBULK is used in v1

- Dockerfile
- build_tests.sh
Updated Dockerfile & entrypoint to support "real" snmpd server.
This makes it easier to test https://github.com/gosnmp/gosnmp/pull/289 for instance.
Signed-off-by: Michel Blanc <mb@devops.works>
> Support for e2e tests against net-snmpd

- mocks/gosnmp_mock.go
Regenerated ``gosnmp_mock.go`` adds ``useResponseSecurityParameters``  parameter to ``UnmarshalTrap()`` mock base method.
> mocks/gosnmp_mock.go: Update UnmarshalTrap mock base method

- Makefile
> Makefile: bump golangci-lint to v1.36.0

- .circleci/config.yml
Add a CI pipeline test to make sure Go generate is up to date.
> Add CI test for go generate

- go.mod
- go.sum
> go.mod: Bump testify to v1.7.0

- gosnmp.go
- helper.go
- marshal.go
- v3.go
- v3_usm.go
Allow use of `errors.Is()` by using %w error format wrapping.
> Use Go 1.13 error wrapping

- helper.go
- marshal.go
This PR is a (non-breaking) iteration on #295 to address the
remaining comments mentioned in issue #293
* Improve integer conversion safety
* Improve error messages
* Fix code styling
* Add uint8 to helper
> marshalPDU(): stricter integer conversion

- walk.go
* Improve snmp packet level error checks in BulkWalk()
Fixes #291
> walk.go: improve BulkWalk error handling

- CHANGELOG.md
- marshal.go
- Add v3 PDU Report documentation
- Add error handling for non-recoverable cases
-  Add validation to prevent calling ``updatePktSecurityParameters`` with non v3 packet 
Fixes  #251  #307
Co-Authored-by: Thomas Casteleyn <thomas.casteleyn@super-visions.com>
> marshal.go: updatePktSecurityParameters called with non v3 packet

- gosnmp.go
* Remove 'double' locking in validateParameters() as write operations to the underlying Logger object are [atomic](https://github.com/golang/go/blob/master/src/log/log.go#L49)
* Simplify flow
> gosnmp.go: remove double locking in validateParameters

- marshal.go
There is currently an issue processing the SNMP Get response:
If the device responded to the snmp get request with an error, for example (tooBig response) when the maximum number of oids was exceeded, then instead of immediately completing the processing of the received packet, the library tries to retry the request again if the number of attempts is specified.
Also, the received error code is lost. It should be in SnmpPacket.Error, but in fact it contains the NoError value.
This fix allows you to stop processing the snmp response, and immediately return the received SNMP error code instead of waiting for retries, saving the error code.
> return received SNMP error code immediately instead wait timeout

- gosnmp.go
- helper.go
- marshal.go
- trap.go
- v3.go
- v3_usm.go
* Delete commented out code.
* Use `errors.New()` for fixed errors.
* Use `%w` for wrapping errors.
* Remove newlines from errors messages.
> Code cleanup

- CHANGELOG.md
- marshal.go
* marshal.go: Add error handling to decryptPacket call in sendOneRequest()
* marshal.go: Add empty/nil packet validation to unmarshalPayload()
Fixes #311
> marshal.go: improve packet validation and error handling

- CHANGELOG.md
- marshal.go
* marshal.go: Fix erroneous on-error continue flow in ``sendOneRequest()`` that caused time-outs after a marshal error.
Fixes #246 
> marshal.go: Fix on-error-continue flow in sendOneRequest

- marshal_test.go
- v3_usm.go
* Fix duplicate description comment for ``UsmSecurityParameters.Description()``
> v3_usm.go: Fix UsmSecurityParameters.Description comment

- helper.go
helper.go: Fix panic in parseRawField when logger is nil
Fixes #327
> helper.go: parseRawField fix nil logger panic

- marshal.go
Add report errors from https://tools.ietf.org/html/rfc3412
Currently, those report errors will lead to generic [`unknown report pdu` message](https://github.com/gosnmp/gosnmp/blob/ed754a519e476a286205b274ff3d8fa22917801e/marshal.go#L119).
---
I saw `snmpUnknownPDUHandlers` error when querying `snmpsim` using wrong context engine id.
The current error message from gosnmp is ` unknown report pdu`.
The report PDU value is like `.1.3.6.1.6.3.11.2.1.3.0 Counter32 99`, `99` being the number of errors.
> Add rfc3412 report errors

- CHANGELOG.md
- gosnmp.go
- helper.go
- helper_test.go
- marshal.go
The marshalOID () and oidToString () functions use the string functions Trim, Split, Join, which work internally with an array of strings. Also, to convert the oid string to an array of numbers and in the opposite direction, an additional array is created inside both marshalOID () and oidToString (), which causes at least twice the load on the GC.
In my case, with parallel polling of 100k + devices, this change in these functions improved performance and CPU load by 10% -15%. The average CPU load dropped from 80% to 65% after. In addition, the total polling time has noticeably decreased.
The second patch (reverted due to broken ci check) concerns the logging function logger.Printf(). Even with logging disabled, the Printf() system call is still called, which, according to pprof, also …
> Improved perfomance

- helper.go
- v3_usm.go
This fix correct SNMPv3 implementation for traps according to :
- RFC3414 for MD5 and SHA1
- RFC7860 for SHA2 (SHA-224, SHA-256, SHA-384, SHA-512)
If a trap arrive and cannot be decoded, there could be an "out of range index". This fix silently fail instead of a panic.
More details in #284
> Fix snmpv3 trap

- CHANGELOG.md
Release v1.32.0
NOTE: This release changes the Logger interface. The loggingEnabled variable has been deprecated.
* [BUGFIX] marshal.go: improve packet validation and error handling #323
* [BUGFIX] marshal.go: Fix on-error-continue flow in sendOneRequest #324
* [BUGFIX] Fix SNMPv3 trap authentication #332
* [CHANGE] New Logger interface has been implemented #329
* [ENHANCEMENT] helper.go: Improved OID marshaling with sub-identifier validation as per rfc2578 section-3.5 #321
* [ENHANCEMENT] Add rfc3412 report errors #333
> Release v1.32.0

- helper.go
- marshal.go
In the decodeValue () function, the msg parameter is always "value". It doesn't make any sense.
Also in this function, the retVal variable can be declared before the function call and passed as a parameter. It will be cheaper than creating it on the heap every time inside decodeValue (). Because:
response.Variables = append(response.Variables, SnmpPDU{oid, decodedVal.Type, decodedVal.Value})
In this case, it is safe. The SnmpPDU is passed the field values, not the structure itself.
It also gives small winnings in both Bytes/op and allocs/op
> helper.go: Improved decodeValue() function

- CHANGELOG.md
- generic_e2e_test.go
- gosnmp.go
- gosnmp_api_test.go
- helper_test.go
- logger.go
- logger_debug.go
- marshal_test.go
- misc_test.go
- trap_test.go
Closes: https://github.com/gosnmp/gosnmp/issues/339
Allow socket binding to a specific local address. Only works for UseUnconnectedUDPSocket = true.
To set the listening address, a new Listen variable has been added with a default value of ":0". This value matches the previously used behavior when using UseUnconnectedUDPSocket = true (bind to 0.0.0.0 with random port)
For example:
```
gosnmp.Default.Listen = "1.2.3.4:161"
```
> Allow binding a socket to a specific local address

- gosnmp.go
- helper.go
- misc_test.go
This is no longer needed since Go1.1
> remove: func uint64ToBigInt(uint64) *big.Int

- helper.go
- marshal.go
- v3.go
- v3_usm.go
* helper.go: add error handling to parseLength to prevent returning invalid data.
follow-up of #354
> helper.go: add error handling to parseLength

- CHANGELOG.md
- marshal.go
Stricter bounds checking for cursor in unmarshalPayload
to ensure it does not exceed ``len(packet)``, preventing
panic when receiving a malformed packet.
Special thanks to Amplia Security for disclosing this issue responsibly.
Fixes #381
> marshal.go: stricter cursor bounds checking in unmarshalPayload

- CHANGELOG.md
NOTE: marshalInt32 now always encodes an integer value in the smallest possible
number of octets as per ITU-T Rec. X.690 (07/2002).
* [ENHANCEMENT] gosnmp/marshalInt32: adhere to ITU-T Rec. X.690 integer encoding #372
* [ENHANCEMENT] parseInt64: throw error on zero length as per X690 #373
* [ENHANCEMENT] helper.go: Interpreting the value of an Opaque type as binary data if the Opaque sub-type cannot be recognized #374
* [ENHANCEMENT] helper.go: Implemented Opaque type marshaling #374
* [BUGFIX] marshal.go: Fixed invalid OpaqueFloat and OpaqueDouble marshaling in marshalVarbind() function #374
* [BUGFIX] marshal.go: stricter cursor bounds checking in unmarshalPayload #384
Signed-off-by: SuperQ <superq@gmail.com>
> Release v1.34.0

- CHANGELOG.md
- interface.go
- mocks/gosnmp_mock.go
- trap.go
- trap_test.go
Hello 👋
When sending INFORMs, the sender may attempt to autodiscover the engineID of the receiving agent. Currently gosnmp does not answer to such requests, this PR is an attempt to fix that using [RFC3414](https://www.rfc-editor.org/rfc/rfc3414#section-3.2).
1. Run the example trapListener
2. Send an inform with snmptrapd like so:
```
snmptrap -v3 -Ci -l authPriv -u user -a SHA -A password -x AES -X password 127.0.0.1:9162 ''  1.3.6.1.4.1.8072.2.3.0.1 1.3.6.1.4.1.8072.2.3.2.1 i 60
```
snmptrapd will first attempt to discover the engineID of the receiver by sending an empty GetRequest PDU (no variable, no authoritativeEngineId).
A compliant implementation should listen for this request and return a Report PDU with the correct authoritativeEngineID.
Because gosnmp does not yet answer to …
> TrapListener: Support authoritative engineID discovery

- CHANGELOG.md
- gosnmp.go
- trap.go
* SendTrap: do not set Reportable MsgFlags for v3 trap as per rfc3412#6.4
Fixes: #391
> SendTrap: do not set Reportable MsgFlags for v3 trap

- examples/linux_vrf/main.go
- gosnmp.go
This patch adds the ability to customize the underlying socket used by GoSNMP which is requiring in some scenario by passing Control func field to Dial. 
A working example of a scenario requiring this feature is also provided (VRF on Linux platform).
> Add Control function in GoSNMP parameters

- gosnmp.go
* gosnmp.go/Set(): permit ObjectIdentifier PDU Type
Fixes #375
> gosnmp.go/Set(): permit ObjectIdentifier PDU Type

- marshal.go
unmarshal getBulk SnmpPacket ,can not get right MaxRepetitions value
when call parseRawField() , the packet Asn1BER type is Integer, then it will call parseInt() to parse MaxRepetitions. the parseInt() only return int type, but in marshal.go assert it as uint32,so you will get 0
> fix:getBulk SnmpPacket can not get right MaxRepetitions value

- gosnmp_api_test.go
- marshal_test.go
- trap_test.go
- v3_usm_test.go
Go 1.16 deprecated io/ioutil. Replace with new functions.
Signed-off-by: SuperQ <superq@gmail.com>
> Remove deprecated io/ioutil

- v3_usm.go
alter  ``extendKeyBlumenthal()`` function to include the privacy passphrase for ``cacheKey()`` calls, to prevent the privacy passphrase that was used for the first connection to be incorrectly reused in any later connections.
fixes #424
> v3_usm.go: add privacy passphrase in extendKeyBlumenthal cacheKey call

- trap.go
Allow sending v1 traps that have no varbinds.  The check for at least 1 pdu, and the TimeTick check on trap.Variables[0] should apply only to v2c/v3.
> Fix SendTrap to allow v1 traps that have no varbinds (like coldStart)

- .circleci/config.yml
- Makefile
- examples/tcp_trapserver/main.go
- logger.go
- logger_debug.go
- v3_credentials_test.go
- v3_usm_test.go
* Add Go 1.20 to tests.
* Add a Makefile linter for the license header.
> Update Go testing

- .circleci/config.yml
- CHANGELOG.md
- Makefile
- go.mod
- go.sum
This release now requires Go 1.20 or higher.
* [ENHANCEMENT] Allow sending v1 traps that have no varbinds #426
* [BUGFIX] Fix getBulk SnmpPacket MaxRepetitions value #413
* [BUGFIX] Refactor security logger #422
* [BUGFIX] Add privacy passphrase in extendKeyBlumenthal cacheKey call #425
* [BUGFIX] unmarshal: fix panic from reading beyond slice #441
> Release v1.36.0

- README.md
- v3_usm.go
- v3_usm_nopwdcache_test.go
- v3_usm_pwdcache_test.go
- v3_usm_test.go
The global password cache is undesirable for higher security applications as a user's cache entry would remain even if the calling package deleted the corresponding `UsmSecurityParameters`.
Disabling this mechanism comes with a significant performance hit, as seen by running the added benchmark tests with the build tag `gosnmp_nopwdcache`.
There is also a middle ground approach, where the calling package can reset the cache by turning it off then on again. This should clear any stale entries and still allow the cache to be leveraged.
> Allow global password cache to be turned off

- examples/trapserver_v3/main.go
- gosnmp.go
- marshal.go
- trap.go
- trap_test.go
- v3.go
- v3_map.go
- v3_usm.go
Greetings 😄  PR addressing issue #302 
This PR adds multiple security parameter support for receiving SNMP V3 traps.
* For the USM model, the identifier for the security parameters to unmarshal with will be the username.
* This is supporting that the configuration of multiple security parameters in the conf.yaml may have usernames with the same identifier, so multiple security parameters can be tried until one satisfies the authentication/privacy protocols
1. Run the listener in `trapserver_v3`
2. Send a trap, examples below:
```
$ snmptrap -v3 -l authPriv -u myuser2 -a MD5 -A mypassword2 -x AES -X myprivacy2 127.0.0.1:9162 '' 1.3.6.1.4.1.8072.2.3.0.1 1.3.6.1.4.1.8072.2.3.2.1 i 123456
$ snmptrap -v3 -l authPriv -u myuser2 -a SHA -A mypassword2 -x DES -X myprivacy2 127.0.0.1:9162 '' …
```
> Support multiple security parameters for receiving SNMP V3 traps

- CHANGELOG.md
* [CHANGE] Refactor netsnmp playback function to use an io.Reader #459
* [FEATURE] Support multiple security parameters for receiving SNMP V3 traps #457
* [ENHANCEMENT] netsnmp tests: tame overzealous file / dir permissions #458
Also update missing v1.37.0 changelog entries.
Fixes: https://github.com/gosnmp/gosnmp/issues/475
> Release v1.38.0

- .circleci/config.yml
- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/golangci-lint.yml
- .golangci.yml
- Makefile
- generic_e2e_test.go
- go.mod
- gosnmp.go
- helper.go
- marshal.go
- trap.go
- v3.go
- v3_credentials_test.go
- v3_usm.go
- walk.go
* Migrate golangci-lint to GitHub actions.
* Update minimum Go version to 1.22.0.
* Update Go test matrix to test latest Go versions.
* Enable dependabot for GitHub actions.
* Update and pin GitHub actions to SHA for supply chain security.
* golangci-lint: Replace exportloopref with copyloopvar.
* golangci-lint: Remove deprecated disabled linters.
* Fixup various golangci-lint issues.
* Mark a number of `gosec` linting issues with nolint. These are all int/uint overflow warnings. These may be intentional, but we need to review them.
> Update build and testing

- trap_test.go
- v3.go
- v3_usm.go
- v3_usm_test.go
In the current state, a `TrapListener` configured with authentication (e.g. `AuthNoPriv`) will accept all incoming packets sent without authentication enabled e.g. via
```
snmptrap -v 3 -l noAuthNoPriv -u my_user localhost:12399 1 coldStart.0   
```
This is due to the fact that the `isAuthentic` function will _only_ iterate over the authentication parameters sent by the client, which is empty for `NoAuthNoPriv`, and therefore completely ignores the authentication settings for the `TrapListener` and potentially for other uses of the USM implementation. Furthermore, the username is not validated in case we do not use a `TrapSecurityParametersTable`.
The current behavior therefore is a security issue as a client can simply bypass security of the server by sending unauthenticated messages! …
> fix: Verify authentication independent of packet msg flags

- trap.go
- v3.go
Hello,
Would you like to review my changes and add a variable size snmp trap message buffer to your code, since in practice it turned out that many snmp trap and inform messages exceed the size of 4 KB.
> Added (t *TrapListener) WithBufferSize(i uint) *TrapListener

- gosnmp.go
- interface.go
- mocks/gosnmp_mock.go
- walk.go
Per RFC 1905 4.2.3 (GetBulkRequest-PDU), non-repeaters is a per-request hint, not a global config value. In all internal usage (e.g. walk.go), it was either 0 or detrimental, causing BulkWalk to degrade into Walk behavior.
To maintain API stability, the field is kept but marked as deprecated and ignored.
fixes #518
Reported-by: Daniel Lepage <daniel.lepage@datadoghq.com>
> Deprecate NonRepeaters

- trap.go
Per RFC 3414 Section 4:
When sending an SNMPv3 InformRequest, the Reportable flag MUST be set in MsgFlags.
This ensures that the authoritative engine will return a Report PDU containing
engineBoots and engineTime for time synchronization which is required before
authenticated communication can succeed. Without this, the engine may reject
the Inform as out-of-time-window or unknown engine.
> Fix: Set the Reportable flag in trap.IsInform messages

- generic_e2e_test.go
- gosnmp.go
Adds a Close() method to GoSNMP that safely closes the network connection. It's safe to call from multiple goroutines and only closes once; subsequent calls are no-ops.
Includes tests for nil connections, double close, and concurrent usage.
Fixes #497
> Add Close method to interface with safe concurrent behavior

- gosnmp.go
- walk.go
Deprecates the legacy use of baseOid (.1.3.6.1.2.1) in walk(), which previously restricted default walks to MIB-2. When no rootOid is provided, we now default to .1.3.6.1, the IANA-assigned 'internet' subtree, which includes both standard (e.g. MIB-2) and vendor-specific branches. This aligns with X.660 OID structure and Net-SNMP behavior, and avoids encoding errors caused by incomplete OIDs.
Fixes #486
Originally reported by Debianov.
> walk(): remove baseOid fallback, default to .1.3.6.1
