gosnmp/gosnmp

helper.go, helper_test.go
=> decode: fix parsing of large counter64/uint64 values

trap.go, trap_test.go
I have added a test for SendTrap and also fixed issue #88.
=> Trap tests/fix #88

v3_usm.go
As we reviewed some weeks ago (https://github.com/soniah/gosnmp/issues/64#issuecomment-292812915)  it seems that there is unneeded  rebuild of the "secret key". 
After apply this fix, the execution speed has been increased  x20, as you can see in the following tool built with current master and with patched version.
````golang
package main
import (
l "github.com/Sirupsen/logrus"
g "github.com/soniah/gosnmp"
"log"
"sync"
"time"
)
func printValue(pdu g.SnmpPDU) error {
return nil
}
func gosnmpGather() {
oids := []string{".1.3", ".1.3", ".1.3", ".1.3"}
time.Sleep(200 * time.Millisecond)
startSnmpStats := time.Now()
var wg sync.WaitGroup
for _, o := range oids {
snmp := initSnmp()
wg.Add(1)
go func(oid string, snmp *g.GoSNMP) {
defer wg.Done()
l.Infof("-------Processing oid: %s", oid)
err := …
```
=> remove unneeded secretkey rebuilding

v3_usm.go
This greatly reduces CPU usage in v3 scenarios using auth, or priv, or both where the calcuated auth/priv keys are discarded, cannot be kept between requests, or must be recalulated (because of an AuthoritativeEngineID change for example).
I understand this is a very naive approach, and has some shortcomings. I'm willing to work (with some direction) on other solutions to reduce/remove the unnecessary recalcuations of the hardened passphrase key.
=> v3 passphrase to passphrase key caching

trap.go
Fixes issue https://github.com/soniah/gosnmp/issues/130
=> fixing build issue

interface.go
Hello,
A few people at Uber including myself needed an interface for GoSNMP in order to create mocks for testing. Hopefully, there are others who will find it useful.
I am open to any suggestions!
Best,
Ivan
=> Add Handler interface

README.md, examples/example/main.go, examples/example2/main.go, examples/example3/main.go, examples/trapsend_v1/main.go, examples/trapsend_v2plus/main.go, examples/trapsend_v3/main.go, examples/trapserver/main.go, examples/walkexample/main.go, examples/walktcpexample/main.go, generic_e2e_test.go, gosnmp.go, gosnmp_api_test.go, helper.go, helper_test.go, interface.go, marshal.go, marshal_test.go, misc_test.go, trap.go, trap_test.go, v3.go, v3_usm.go, walk.go
Hi @SuperQ, I've updated the README - please let me know if you want any changes.
=> update README, copyright

README.md
=> Replace travis shield with circleci in readme

marshal_test.go
add error handling to TestSendOneRequest_dups and BenchmarkSendOneRequest
=> marshal_test.go: Add error handling

README.md
=> README.md: Fix CircleCI widget link

CHANGELOG.md, gosnmp.go, interface.go, marshal.go, mocks/gosnmp_mock.go
Fix for signedness issue in marshalPDU() causing
agents to refuse responding if MaxRepetitions was > 127.
Fixes #293
=> marshal.go: Fix signedness issue in marshalPDU()

asn1ber_string.go, snmperror_string.go, snmpv3authprotocol_string.go
Apply latest stringers from ``go generate``
=> gosnmp: Update stringers

RELEASE.md
Add RELEASE.md steps from @SuperQ 
=> gosnmp: Add RELEASE.md

AUTHORS.md, CHANGELOG.md
* Update AUTHORS.md
* Update CHANGELOG.md
=> Release v1.30.0

examples/example3/main.go
Without setting the timeout, example3 is always fail.
Signed-off-by: Hu Keping <hukeping@huawei.com>
=> Add timeout to example3

CHANGELOG.md
=> Release v1.31.0

marshal.go
Remove extra whitespace.
Signed-off-by: SuperQ <superq@gmail.com>
=> Minor error string cleanup

README.md
Add BulkWalkAll description to the list of functions
=> docs(readme): add BulkWalkAll description

examples/logger/main.go
* Add logger example that was mentioned in #329 PR thread.
=> examples/logger: Add logger examples

examples/Hex-String/main.go
Signed-off-by: raojiajun <13694846652@163.com>
=> Add Hex-String solutions to examples

CHANGELOG.md
* [BUGFIX] address panics, add tests, fuzzing #443
=> Release v1.36.1

trap.go
- Ensure idempotent and thread-safe Close behavior.
- Close connection for both TCP and UDP without protocol checks.
- Use atomic operations for safer concurrent handling.
- Await "done" signal before complete closure, ensuring clean shutdown.
Fixes:
- Address potential issue where the connection might not be closed in certain conditions
Enhances:
- Configurable TrapListener.CloseTimeout with a default of 3 seconds.
=> Refactor TrapListener's Close Method

marshal.go
fixes gosnmp/gosnmp#450  and also unblocks gosnmp/gosnmp#448 (first test passes after this is merged)
=> Allow RequestID to be shrunk if possible

.circleci/config.yml
Add a 60s fuzzing test to the CI test pipeline.
=> Add fuzzing to CI

netsnmp/gosnmp_playback.go
Avoid unnecessary casting of byte slice to string by using a base64 stream decoder atop an io.Reader (the os.File). Make error handling a bit more granular.
=> Refactor netsnmp playback function to use an io.Reader

helper.go, helper_test.go, marshal.go
* marshalUint64: Add comments, error handling and tests.
=> marshalUint64: Add comments, error handling and tests
